name: Build PS3 PKG

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps3dev/ps3dev:latest
    steps:
    - uses: actions/checkout@v3

    - name: Build with PSL1GHT
      run: |
        make

    - name: Upload PKG Artifact
      uses: actions/upload-artifact@v3
      with:
        name: CustomPlayerPKG
        path: ./*.pkg
